version: '3.8'
services:
  app:
    build: ./API/.
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./dbmongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
volumes:
  dbmongodb: