version: '3.8'
services:
  app:
    build: ./API/.
    ports:
      - 3000:3000
    depends_on:
      - postgresqldb
  
  postgresqldb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./dbpostgresql:/var/lib/postgresql/data
volumes:
  dbpostgresql: